name: syed cicd
on:
  push:
    branches:
      - main 
jobs:
  dev:
    name: "deply in dev"
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello dev"
  test:
    name: "test phase"
    runs-on: ubuntu-latest
    run: sudo apt update -y
 
